# Generated by Django 5.1.5 on 2025-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertenantmembership",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
