//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub mod prelude;

pub mod chunks;
pub mod documents;
pub mod knowledge_bases;
pub mod tenants;
pub mod user_tenant_memberships;
pub mod users;
