//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::knowledge_bases::Entity as KnowledgeBases;
pub use super::tenants::Entity as Tenants;
pub use super::user_tenant_memberships::Entity as UserTenantMemberships;
pub use super::users::Entity as Users;
