# Generated by Django 5.2 on 2025-04-21 06:55

import documents.utils
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunking_error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='chunking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default=documents.utils.DocumentChunkingStatus['PENDING'], max_length=20),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
