# Generated by Django 5.2 on 2025-04-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_chunking_error_document_chunking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='character_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chunk',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='chunk_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
